languages = (
    ('afar', 'afar'),
    ('abkhazian', 'abkhazian'),
    ('afrikaans', 'afrikaans'),
    ('akan', 'akan'),
    ('albanian', 'albanian'),
    ('amharic', 'amharic'),
    ('arabic', 'arabic'),
    ('aragonese', 'aragonese'),
    ('armenian', 'armenian'),
    ('assamese', 'assamese'),
    ('avaric', 'avaric'),
    ('avestan', 'avestan'),
    ('aymara', 'aymara'),
    ('azerbaijani', 'azerbaijani'),
    ('bashkir', 'bashkir'),
    ('bambara', 'bambara'),
    ('basque', 'basque'),
    ('belarusian', 'belarusian'),
    ('bengali', 'bengali'),
    ('bihari languages', 'bihari languages'),
    ('bislama', 'bislama'),
    ('tibetan', 'tibetan'),
    ('bosnian', 'bosnian'),
    ('breton', 'breton'),
    ('bulgarian', 'bulgarian'),
    ('burmese', 'burmese'),
    ('catalan; valencian', 'catalan; valencian'),
    ('czech', 'czech'),
    ('chamorro', 'chamorro'),
    ('chechen', 'chechen'),
    ('chinese', 'chinese'),
    ('chuvash', 'chuvash'),
    ('cornish', 'cornish'),
    ('corsican', 'corsican'),
    ('cree', 'cree'),
    ('welsh', 'welsh'),
    ('czech', 'czech'),
    ('danish', 'danish'),
    ('german', 'german'),
    ('greek', 'greek, Modern (1453-)'),
    ('english', 'english'),
    ('esperanto', 'esperanto'),
    ('estonian', 'estonian'),
    ('basque', 'basque'),
    ('ewe', 'ewe'),
    ('faroese', 'faroese'),
    ('persian', 'persian'),
    ('fijian', 'fijian'),
    ('finnish', 'finnish'),
    ('french', 'french'),
    ('western frisian', 'western frisian'),
    ('fulah', 'fulah'),
    ('georgian', 'georgian'),
    ('german', 'german'),
    ('gaelic', 'gaelic; Scottish Gaelic'),
    ('irish', 'irish'),
    ('galician', 'galician'),
    ('manx', 'manx'),
    ('greek', 'Greek, Modern (1453-)'),
    ('guarani', 'Guarani'),
    ('gujarati', 'Gujarati'),
    ('haitian', 'Haitian; Haitian Creole'),
    ('hausa', 'Hausa'),
    ('hebrew', 'Hebrew'),
    ('herero', 'Herero'),
    ('hindi', 'Hindi'),
    ('hiri motu', 'Hiri Motu'),
    ('croatian', 'Croatian'),
    ('hungarian', 'Hungarian'),
    ('armenian', 'Armenian'),
    ('igbo', 'Igbo'),
    ('icelandic', 'Icelandic'),
    ('ido', 'Ido'),
    ('sichuan yi', 'Sichuan Yi; Nuosu'),
    ('inuktitut', 'Inuktitut'),
    ('interlingue', 'Interlingue; Occidental'),
    ('interlingua', 'Interlingua (International Auxiliary Language Association)'),
    ('indonesian', 'Indonesian'),
    ('inupiaq', 'Inupiaq'),
    ('icelandic', 'Icelandic'),
    ('italian', 'Italian'),
    ('javanese', 'Javanese'),
    ('japanese', 'Japanese'),
    ('kalaallisut', 'Kalaallisut; Greenlandic'),
    ('kannada', 'Kannada'),
    ('kashmiri', 'Kashmiri'),
    ('georgian', 'Georgian'),
    ('kanuri', 'Kanuri'),
    ('kazakh', 'Kazakh'),
    ('central khmer', 'Central Khmer'),
    ('kikuyu', 'Kikuyu; Gikuyu'),
    ('kinyarwanda', 'Kinyarwanda'),
    ('kirghiz', 'Kirghiz; Kyrgyz'),
    ('komi', 'Komi'),
    ('kongo', 'Kongo'),
    ('krean', 'Korean'),
    ('kuanyama', 'Kuanyama; Kwanyama'),
    ('kurdish', 'Kurdish'),
    ('lao', 'Lao'),
    ('latin', 'Latin'),
    ('latvian', 'Latvian'),
    ('limburgan', 'Limburgan; Limburger; Limburgish'),
    ('lingala', 'Lingala'),
    ('lithuanian', 'Lithuanian'),
    ('luxembourgish', 'Luxembourgish; Letzeburgesch'),
    ('luba-katanga', 'Luba-Katanga'),
    ('ganda', 'Ganda'),
    ('macedonian', 'Macedonian'),
    ('marshallese', 'Marshallese'),
    ('malayalam', 'Malayalam'),
    ('maori', 'Maori'),
    ('marathi', 'Marathi'),
    ('malay', 'Malay'),
    ('micmac', 'Micmac'),
    ('macedonian', 'Macedonian'),
    ('malagasy', 'Malagasy'),
    ('maltese', 'Maltese'),
    ('mongolian', 'Mongolian'),
    ('malay', 'Malay'),
    ('burmese', 'Burmese'),
    ('panjabi', 'Panjabi; Punjabi'),
    ('persian', 'Persian'),
    ('pali', 'Pali'),
    ('polish', 'Polish'),
    ('portuguese', 'Portuguese'),
    ('pushto', 'Pushto; Pashto'),
    ('quechua', 'Quechua'),
    ('romansh', 'Romansh'),
    ('romanian', 'Romanian; Moldavian; Moldovan'),
    ('tamil', 'Tamil'),
    ('telugu', 'Telugu'),
    ('chinese', 'Chinese'),
    ('zulu', 'Zulu')
)